### ISSUE TITLE
Changing comment to theme or mute kill the colorization of all

### ISSUE THREAD

**Issue by Cog-g** [xcezzz/semanticolor#15] opened 2017-01-10 09:50 UTC
Hi, I'm changing the comment from `contrast` to `theme` or `mute` for Ruby language, then I reload Atom, and I loose the colorization, like the plugin was not activated.

The only value that reactivate the colorization is `contrast`

on Windows 10, insider build 14986

**Comment by sharedprophet** [comment] 2017-01-10 16:45
This is a duplicate of #14. Will do some more work on it soon. Thanks.

**Closed by sharedprophet** 2017-01-10 16:45 UTC
